plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\vitor\\Downloads\\Backup notebook vitor 17-04-26\\Area\\Marcas\\Merkos\\feedback\\vivalamesa-deploy"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]